### ISSUE TITLE
conflicting definition of "tick" and its usage

### ISSUE THREAD

**Issue by niknal357** [Scrap-Mechanic-Logic-Consortium/SMLC-Terminology#1]
we currently define a tick as the computation of and update to the next logic state, but that seems to be in contradiction with the phrase "one tick pulse" which means that the logic turns on one tick, and turns off on the next. is this not a valid phrase? does it require its own definition? does "tick" need to be redefined to be more versatile?

**Comment by codemaker4** [comment]
In a discord voice chat, Niknal and I concluded that this is not actually a pressing issue, as the saying "one tick pulse" still has a clear meaning in practice.
